jobs:
  publish:
    name: Publish Maven Central Release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Configure JDK
      uses: actions/setup-java@v3.11.0
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      name: Set Release Version Name
      run: sed -e s/-SNAPSHOT//g -i gradle.properties;
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Publish Maven Central Release
      run: ./gradlew publish
name: Publish Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
